export {default as Nav} from './nav-bar'
export {default as Home} from './home'
export {default as About} from './about'
export {default as Projects} from './projects'
export {default as Contact} from './contact'
